package com.emiprotecciones;

import com.mojang.brigadier.arguments.StringArgumentType;
import com.mojang.brigadier.context.CommandContext;
import net.fabricmc.api.ModInitializer;
import net.fabricmc.fabric.api.command.v2.CommandRegistrationCallback;
import net.minecraft.server.command.CommandManager;
import net.minecraft.server.command.ServerCommandSource;
import net.minecraft.server.network.ServerPlayerEntity;
import net.minecraft.server.world.ServerWorld;
import net.minecraft.text.Text;
import net.minecraft.util.math.BlockPos;

/**
 * Compatibility parser for the GUI management command.
 *
 * The original command used StringArgumentType.word() for a token formatted as
 * x,y,z. Brigadier's unquoted word parser does not allow commas, so commands
 * generated by the GUI stopped at the first comma. This secondary branch uses
 * a greedy payload and parses the already-existing GUI format safely on the
 * server. Keeping the payload format compatible means all alpha.4 GUI buttons
 * (preview, guests and permissions) are fixed at once.
 */
public final class ManagementCommandCompat implements ModInitializer {
    @Override
    public void onInitialize() {
        CommandRegistrationCallback.EVENT.register((dispatcher, registryAccess, environment) -> dispatcher.register(
                CommandManager.literal("emiprotecciones")
                        .then(CommandManager.literal("manage")
                                .then(CommandManager.argument("payload", StringArgumentType.greedyString())
                                        .executes(ManagementCommandCompat::executePayload)))
        ));
    }

    private static int executePayload(CommandContext<ServerCommandSource> context) {
        if (!(context.getSource().getEntity() instanceof ServerPlayerEntity player)) {
            return 0;
        }

        String payload = StringArgumentType.getString(context, "payload").trim();
        if (payload.isEmpty()) {
            return fail(player, "Comando de protección incompleto.");
        }

        String[] tokens = payload.split("\\s+");
        if (tokens.length < 2) {
            return fail(player, "Comando de protección incompleto.");
        }

        String[] coords = tokens[0].split(",");
        if (coords.length != 3) {
            return fail(player, "Posición de protección inválida.");
        }

        final BlockPos pos;
        try {
            pos = new BlockPos(
                    Integer.parseInt(coords[0]),
                    Integer.parseInt(coords[1]),
                    Integer.parseInt(coords[2])
            );
        } catch (NumberFormatException ignored) {
            return fail(player, "Posición de protección inválida.");
        }

        ServerWorld world = context.getSource().getWorld();
        if (!(world.getBlockEntity(pos) instanceof EmiProtecciones.ProtectionCoreBlockEntity core)) {
            return fail(player, "No hay una protección válida en esa posición.");
        }
        if (!core.canManage(player)) {
            return fail(player, "Solo el propietario puede administrar esta protección.");
        }
        if (core.getFlanClaimId() == null) {
            return fail(player, "Esta protección no tiene un claim de Flan asociado.");
        }

        String action = tokens[1];
        return switch (action) {
            case "preview" -> preview(player, core);
            case "add" -> manageGuest(player, world, core, tokens, true);
            case "remove" -> manageGuest(player, world, core, tokens, false);
            case "guestperm" -> managePermission(player, world, core, tokens, false);
            case "globalperm" -> managePermission(player, world, core, tokens, true);
            default -> fail(player, "Acción de protección desconocida.");
        };
    }

    private static int preview(ServerPlayerEntity player, EmiProtecciones.ProtectionCoreBlockEntity core) {
        core.startPreview();
        player.sendMessage(Text.literal("§d✦ Mostrando límites de la protección."), true);
        return 1;
    }

    private static int manageGuest(
            ServerPlayerEntity player,
            ServerWorld world,
            EmiProtecciones.ProtectionCoreBlockEntity core,
            String[] tokens,
            boolean add
    ) {
        if (tokens.length < 3) {
            return fail(player, "Falta el nombre del jugador.");
        }

        String name = tokens[2];
        if (!name.matches("[A-Za-z0-9_]{1,16}")) {
            return fail(player, "Nombre de jugador inválido.");
        }

        boolean ok = add
                ? FlanBridge.addGuest(world, core.getFlanClaimId(), player, name)
                : FlanBridge.removeGuest(world, core.getFlanClaimId(), player, name);

        if (add) {
            player.sendMessage(
                    Text.literal(ok
                            ? "§d✦ " + name + " §fahora está permitido en tu protección."
                            : "§c✦ No se pudo añadir a " + name + ". Debe estar conectado."),
                    false
            );
        } else {
            player.sendMessage(
                    Text.literal(ok
                            ? "§d✦ " + name + " §fya no está permitido en tu protección."
                            : "§c✦ No se pudo quitar a " + name + ". Debe estar conectado."),
                    false
            );
        }
        return ok ? 1 : 0;
    }

    private static int managePermission(
            ServerPlayerEntity player,
            ServerWorld world,
            EmiProtecciones.ProtectionCoreBlockEntity core,
            String[] tokens,
            boolean global
    ) {
        if (tokens.length < 4) {
            return fail(player, "Faltan datos del permiso.");
        }

        String permission = tokens[2];
        if (!tokens[3].equalsIgnoreCase("true") && !tokens[3].equalsIgnoreCase("false")) {
            return fail(player, "El valor del permiso debe ser true o false.");
        }
        boolean allow = Boolean.parseBoolean(tokens[3]);

        boolean ok = global
                ? FlanBridge.setGlobalPermission(world, core.getFlanClaimId(), player, permission, allow)
                : FlanBridge.setGuestPermission(world, core.getFlanClaimId(), player, permission, allow);

        player.sendMessage(
                Text.literal(ok
                        ? (global
                            ? "§d✦ Regla de parcela actualizada: §f" + permission + " §7→ " + (allow ? "§aACTIVA" : "§cBLOQUEADA")
                            : "§d✦ Permiso actualizado: §f" + permission + " §7→ " + (allow ? "§aPERMITIR" : "§cBLOQUEAR"))
                        : "§c✦ No se pudo modificar ese permiso."),
                true
        );
        return ok ? 1 : 0;
    }

    private static int fail(ServerPlayerEntity player, String message) {
        player.sendMessage(Text.literal("§c✦ " + message), true);
        return 0;
    }
}
